### PR TITLE
[refactor] Literature with Recoil implementation

### PR DESCRIPTION
**Pull request by carcruz**
Ready for the review!

Major updates
- Recoil implementation
- Fix a bug related to a missing publication from EuropePMC, that used to make the component crash
- Skeleton and Grow animations implementation
- Cache results from EuropePMC

@andrewhercules now we have the ability to know which and where we are missing results from EuropePMC. For now, I added a row (image below), but we can either hide it or show a different component.

Screen Shot 2021-06-17 at 4 30 08 AM

### CODE REVIEW

**Comment by mkarmona** [comment]
@carcruz it sounds great! I cannot wait to review it. I will do the data model review later today thanks!

**Comment by andrewhercules** [comment]
Thanks @carcruz! I have tested it with different combinations and noticed a few things:

1. There is no ability to see more than 5 results - both the "show more" functionality and pagination are not working. 

2. The component retains the state - and Europe PMC API results - if a user visits another page. For example, I visited the [renal cell carcinoma page](https://deploy-preview-386--platform-app.netlify.app/disease/EFO_0000681) and filtered for targets. When I visited the [ulcerative colitis](https://deploy-preview-386--platform-app.netlify.app/disease/EFO_0000729) and [rofecoxib](https://deploy-preview-386--platform-app.netlify.app/drug/CHEMBL122) profile pages, the Bibliography component shows me the results and options from the initial state on the renal cell carcinoma profile page and it will not allow me to click any of the checkboxes or concept chips - see the screenshots below. The only way to reset the component was to refresh the page and clear my cache.

Screenshot 2021-06-17 at 12 53 35
Screenshot 2021-06-17 at 12 53 16
Screenshot 2021-06-17 at 12 52 27

3. If I click one of the pagination options, I can no longer click any of the concept chips.

4. For the rows where there is no abstract/citation, can you please adjust and temporarily hide the result? From a quick review of various examples, these results are likely to be preprints (e.g. [32818209](https://pubmed.ncbi.nlm.nih.gov/32818209/)). @mkarmona and @d0choa, we will want to consider how we integrate preprints into the literature index because different sources handle them in different ways. For example, preprints indexed by EuropePMC have a PPR identifier and no PubMed ID whereas preprints in PubMed have a PubMedID. It will also require a change to the Europe PMC API query as preprint data is served from the `PPR` database.

**Comment by carcruz** [comment]
Hey @andrewhercules, thanks a lot for your review. Most of the errors were caused by an error on the `handlePageChange` event. Should be working and refreshing correctly now. 

Also, missing literatures are hidden now 👍

**Review by andrewhercules — APPROVED** [review]
Looks great - thank you for making the changes! 👍

**Review by mirandaio — APPROVED** [review]

**Pull request merged**
