### PR TITLE
Known Drugs sources sidebar and fixes

### PR DESCRIPTION
**Pull request by javfg**
The sources column of the clinical trials information in known drugs widget shows a lot of information, so when there is more than one element to display in a cell, a sidebar will open with details.

This PR also includes:

* Adding a parameter to the new table component for a custom pagination component. The known drugs backend does not handle skipping to the last page very well for now, so it's better to not show buttons for first/last.
* Fixing Known Drugs widgets summaries.

Preview here: https://5ede0e8031449c00079e3917--platform-app.netlify.app/

### CODE REVIEW

**Comment by andrewhercules** [comment]
@LucaFumis could you please review?

**Comment by andrewhercules** [comment]
@javfg can I request the following changes?

1. In the target profile page summary widget, can we update the summary widget component to read `n drugs in clinical trials` where n is the `target.knownDrugs.uniqueDrugs` value? For example, for ESR1, it would be 24.

2. In the disease profile page summary widget, can we update the summary widget component to read `n drugs in clinical trials` where n is the `disease.knownDrugs.uniqueDrugs` value? For example, for osteoporosis, it would be 46.

3. In the drug profile page summary widget, can we update the summary widget component to read `n clinical trial records` where n is the `drug.knownDrugs.count` value? For example, for metformin, it would be 33,558.

**Comment by javfg** [comment]
Changes are up! https://5ede408be79e0900088cf781--platform-app.netlify.app/

**Comment by andrewhercules** [comment]
Awesome - thank you @javfg 👍

**Comment by LucaFumis** [comment]
Looks good but I understand the API has changed, so I imagine it will require some changes as it's not currently working.

**Pull request merged**
