### PR TITLE
Add Toxicity tables to the Safety section

### PR DESCRIPTION
**Pull request by fedde-s**
Porting logic previously implemented in the 20.04 release.

### CODE REVIEW

**Comment by fedde-s** [comment]
This should address issue opentargets/platform#1034 (a follow-up to [opentargets/platform#1017](https://github.com/opentargets/platform/issues/1017#issuecomment-626708086)).

**Comment by fedde-s** [comment]
The ‘Source’ column contains a link in the tables. In the file downloads, I export the URL there, but as opposed to the publication URL in the **Adverse effects** and **Safety risk information** tables, the URL seems to be the same for all rows here. Let me know if you think I should put the name of the data source (the text of the link) in these exported fields instead.

**Comment by fedde-s** [comment]
Should I also push a commit to hide the **Adverse effects** and **Safety risk information** tables when they are empty?

**Comment by andrewhercules** [comment]
> Should I also push a commit to hide the **Adverse effects** and **Safety risk information** tables when they are empty?

@fedde-s yes if you could do that, it would be much appreciated. These data sets only cover a small portion of targets so if we could hide when the data is not available - as we currently do in the Angular app - that would be great!

**Comment by andrewhercules** [comment]
> The ‘Source’ column contains a link in the tables. In the file downloads I export the URL there, but as opposed to the publication URL in the **Adverse effects** and **Safety risk information** tables, the URL seems to be the same for all rows here. Let me know if you think I should put the data source name (the link text/label) in these exported fields instead.

@fedde-s the URL is fine. It is the same because we had to separate each data source - eTOX and Tox21 - into its own data table because of the differences in the underlying data. However, one of our informatics projects is curating more data for these tables and so eventually we will have different URLs in the source column 👍

**Comment by andrewhercules** [comment]
@LucaFumis can you please review? 

I have checked the deploy preview (e.g. [ESR1](https://5ecd1cf6c478e80006463fe8--platform-app.netlify.app/target/ENSG00000091831) and [CDK2](https://5ecd1cf6c478e80006463fe8--platform-app.netlify.app/target/ENSG00000123374) and [MTOR](https://5ecd1cf6c478e80006463fe8--platform-app.netlify.app/target/ENSG00000198793)) and all scenarios look good to me 👍

**Comment by fedde-s** [comment]
@andrewhercules:
> if we could hide when the [ **Adverse effects** and **Safety risk information** ] data is not available - as we currently do in the Angular app - that would be great!

Done! Feel free to squash the commits as you see fit, or to ask me to squash/reorder some of them.

**Comment by fedde-s** [comment]
> (e.g. [ESR1](https://5ecd1cf6c478e80006463fe8--platform-app.netlify.app/target/ENSG00000091831) and [CDK2](https://5ecd1cf6c478e80006463fe8--platform-app.netlify.app/target/ENSG00000123374) and [MTOR](https://5ecd1cf6c478e80006463fe8--platform-app.netlify.app/target/ENSG00000198793))

An example of a target with both toxicity tables: [ABCG2](https://deploy-preview-151--platform-app.netlify.app/target/ENSG00000118777)
And one with only an eTOX table: [SLC28A2](https://deploy-preview-151--platform-app.netlify.app/target/ENSG00000137860)

**Pull request merged**
