### PR TITLE
Create new publications drawer

### PR DESCRIPTION
**Pull request by carcruz**
Publications drawer working on evicende page

### CODE REVIEW

**Comment by andrewhercules** [comment]
@carcruz, looks great and very helpful for users looking for more information about a publication.

Can we please make a few adjustments?

- [ ] Use FontAwesome icons available from [existing NPM `fontawesome` package](https://github.com/opentargets/platform-app/blob/bffecc589f074627b5b236e1f07b6c5a240c531c/package.json#L16)
- [ ] Change loading text to "Loading Europe PMC search results"
- [ ] Remove "Publications" column label in data table component 
- [ ] Remove "Locked Access" icon and label
- [ ] If `"inEPMC": "Y"` or `"inPMC": "Y"`, display the [file-alt icon](https://fontawesome.com/icons/file-alt?style=regular) and the label "Full text available" in Open Targets Grey `#5a5f5f` 

For the Cancer Gene Census entries for [EGFR and lung cancer](https://deploy-preview-319--platform-app.netlify.app/evidence/ENSG00000146648/MONDO_0008903), I notice that the response is not cached. Is there a way to cache the response in case a user accidentally closes the drawer and reopens it? -

**Comment by d0choa** [comment]
Other comments that came out in conversation with @mkarmona:
- [ ] remove the mouse-over interaction on "Locked Access" and "Open Access"
- [ ] handle undefined values - E.g. Noonan Syndrome + BRAF + ClinVar + rs180177042 (PMID:25173338)
- [ ] handle empty values in journal string, for example in books - E.g. Noonan Syndrome + BRAF + ClinVar + rs180177042 (PMID: 20301303)
- [ ] search breaking on previous examples

A nice to have for the future:
- [ ] Highlighting of the search results

**Comment by d0choa** [comment]
@carcruz you can include the widget in the OT genetics portal widget as well. The column looks a bit different but it can have the same functionality.

**Comment by carcruz** [comment]
@d0choa HTML fixed and working correctly now.

Adding the drawer to the OT genetics, going to add a `custom label` prop to handle these edge cases

**Comment by d0choa** [comment]
All looks great to me! Good job

**Comment by LucaFumis** [comment]
Hey @carcruz this looks really great! 
Only two things I noticed:
1 - pagination bug: for cases with number of publications between 5 and 10, only the first 5 are displayed, but there are no pagination options showing.
2 - showing abstract (minor issue, I guess we can live with it): I open the abstract for, say, the second paper in the list, then move to the second page of papers, then the table would show the abstract for paper 12 (i.e. the second item on page 2).

**Comment by carcruz** [comment]
I reviewed @LucaFumis comments, the pagination bug is fixed by setting the initial page count to 10 (DataTable component default).
The second point is a minor issue, we going to leave it for now, in the future we will basically add a more complex state implementation on each individual publication.

**Review by LucaFumis — APPROVED** [review]
Thank you @carcruz - looks great!

**Pull request merged**
