### PR TITLE
Target - Update Gene Ontology widget

### PR DESCRIPTION
**Pull request by carcruz**
https://github.com/opentargets/platform/issues/1675

### CODE REVIEW

**Comment by andrewhercules** [comment]
Thanks @carcruz!

After reviewing with @d0choa, can we please make the following changes?

- [ ] Fix the search function — currently it does not work, but users should be able to search

- [ ] Add the "Show more rows" functionality to the table

- [ ] Sort the table alphabetically by the "Category" column

- [ ] In the "Source" column, can we please parse the response and for non-PMID entries (e.g. GO, Reactome, DOI), can we remove the `:ID-value` (e.g. `Reactome:R-HSA-170076` would become `Reactome`, `GO_REF:0000043` would become `GO_REF`)

_Before:_
Screenshot 2021-09-01 at 17 08 17

_After:_
Screenshot 2021-09-01 at 17 09 27

- [ ] Update the tooltips in the "Evidence code" column to use  the [GeneOntologyEvidenceCodeMappings.json](https://github.com/opentargets/platform-app/files/7092893/GeneOntologyEvidenceCodeMappings.json.zip) file and display the `evidenceLabel` and `evidenceCategory`  and display a link labelled `Gene Onotology wiki` using the `evidenceSourceUrl`:

Screenshot 2021-09-01 at 17 34 07

*Note: the mapping file is available on the [team Google Drive
](https://docs.google.com/spreadsheets/d/1WqqZ05_l0Dl_vikStldr4nyt-oqSl34WYmQU33C-YeI)

**Comment by carcruz** [comment]
The comments above were addressed. 

Can we validate the `GO_REF ` URL for the source column? I have seen some broken links (e.g. https://identifiers.org/0000107%7D )

**Comment by andrewhercules** [comment]
> Can we validate the `GO_REF ` URL for the source column? I have seen some broken links (e.g. https://identifiers.org/0000107%7D )

@carcruz, can you provide me with an Ensembl ID so that I can check? The IDs should work and resolve to a GitHub page (e.g. https://identifiers.org/GO_REF:0000107)

**Comment by andrewhercules** [comment]
Looks great @carcruz! Thank you for the changes! 😄

**Review by LucaFumis — APPROVED** [review]
Thanks @carcruz - LGTM
I noticed Github flags a "no new line at end of file" in GeneOntologyEvidenceCodeMappings.json - not sure whether that causes issues

**Pull request merged**
