### PR TITLE
Switch react-select for material-ui autocomplete

### PR DESCRIPTION
**Pull request by javfg**
This lets us remove `react-select` library from the bundle, and unifies the look and feel of dropdowns.

### CODE REVIEW

**Comment by javfg** [comment]
@fedde-s just FYI, this changed your `FilteringOtTableRF` component slightly. Specifically, the `options` array no longer contains objects with `label` and `value` fields, just values.

**Comment by fedde-s** [comment]
From a brief look at the code I see no problem with that, as (unless I'm misreading) that `options` array was just an internal implementation detail of `FilteringOtTableRF` to match the API of the library that it was using before, and not one of `FilteringOtTableRF`'s props. Thanks for the heads-up though!

**Comment by javfg** [comment]
This is breaking `ot-ui`, I'm pulling it until I can solve the problem.

**Comment by javfg** [comment]
This PR removes all dependencies to `react-select` from the code, but it is still required to build `ot-ui` as a peer dependency. To remove the library, its dependency has to be removed from `ot-ui` also.

**Review by LucaFumis — APPROVED** [review]
Thanks @javfg, looks OK

**Pull request merged**
